apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  username: {{ .Values.mysql.username | b64enc | quote }}
  password: {{ .Values.mysql.rootPassword | b64enc | quote }}
  database: {{ .Values.mysql.database | b64enc | quote }}