apiVersion: v1
kind: Service
metadata:
  name: chatify-php
spec:
  type: {{ .Values.service.type }}
  selector:
    app: chatify-php
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 80
