image:
  repository: vivekshahi918/chatify
  tag: 'chatify-10cff40'

mysql:
  image: mysql:5.7.42  # pinned patch version
  rootPassword: root
  database: chatify
  username: root
  pvcSize: 5Gi

service:
  type: LoadBalancer  # change to NodePort for local dev if needed
  port: 80
